### ISSUE TITLE
Error with on-modify.timewarrior when annotating a task

### ISSUE THREAD

**Issue by bepolymathe** [GothenburgBitFactory/timewarrior#442]
Hi,

I just installed fedora on a new machine, then taskwarrior. I have a problem when I try to modify (annotate for example) a task.

`task diagnostic` return 

```
task 2.5.3
   Platform: Linux

Compiler
    Version: 11.1.1 20210428 (Red Hat 11.1.1-1)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Jun  3 2021 00:00:00
      CMake: 3.19.7
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.2
 Build type: 

Configuration
       File: /home/bepolymathe/.taskrc (found), 3249 bytes, mode 100664
       Data: /home/bepolymathe/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: inthe.am:53589
         CA: /home/bepolymathe/.task/ca.crt, readable, 2405 bytes
Certificate: /home/bepolymathe/.task/private.certificate.pem, readable, 2710 bytes
        Key: /home/bepolymathe/.task/private.key.pem, readable, 17761 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: inthe_am/bepolymathe2021/************************************

Hooks
     System: Enabled
   Location: /home/bepolymathe/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 255x52
       Dups: Scanned 57 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 57 tasks for broken references:
             No broken references found
```

If i try to annotate a task...

```
[15:02:38]  ~ : task 31 annotate "add something"
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 28: from : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 30: import : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 31: import : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 32: import : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 41: try: : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 42: input_stream : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 43: except : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 44: input_stream : commande introuvable
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 47: erreur de syntaxe près du symbole inattendu « ( »
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 47: `old = json.loads(input_stream.readline().decode("utf-8", errors="replace"))'
Hook Error: Expected feedback from failing hook script: on-modify.timewarrior
```

Would you have an idea ?

**Comment by bepolymathe** [comment]
And to complete 

```
[22:15:35]  ~ : timew diagnostics 

timew 1.4.3
       Platform: Linux

Compiler:
        Version: 11.1.1 20210531 (Red Hat 11.1.1-3)
           Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
     Compliance: C++11

Build Features
          Built: Jun 17 2021 00:00:00
          CMake: 3.20.3
     Build type: 

Configuration
  TIMEWARRIORDB: -
            Cfg: /home/bepolymathe/.timewarrior/timewarrior.cfg (-rw- 0 bytes)
       Database: /home/bepolymathe/.timewarrior (drwx 58 bytes)
        $EDITOR: vim
    Color theme: Built-in default
                 00 01 02 03 04 05 06 07 08 09 10 11 12

Extensions
       Location: /home/bepolymathe/.timewarrior/extensions (drwx 0 bytes)
               (None)

```

**Comment by lauft** [comment]
Hi @bepolymathe!
The output of the hook script looks odd to me
```
/home/bepolymathe/.task/hooks/on-modify.timewarrior: ligne 28: from : commande introuvable
```
It seems to me as if it is not interpreted as a python script... 

Do you have python3 installed? 
I assume you are using the most recent version of the hook script from your Timewarrior 1.4.3 installation...

**Comment by bepolymathe** [comment]
Hi @lauft 

Yes i have `python3-3.9.6-2.fc34.x86_64` installed and yes for version...

```
[22:42:07]  ~ : timew --version
1.4.3
```
:thinking:

**Comment by bepolymathe** [comment]
And for rights

```
[22:42:49]  ~ : cd .task/hooks/
[22:44:11]  ~/.task/hooks : ls -la
total 4
drwxr-xr-x. 1 bepolymathe bepolymathe   42 23 juil. 22:00 .
drwxr-xr-x. 1 bepolymathe bepolymathe  192 23 juil. 21:52 ..
-rwxr-xr-x. 1 bepolymathe bepolymathe 3183 22 juil. 22:59 on-modify.timewarrior

```

**Comment by bepolymathe** [comment]
Strange for me too...

**Comment by lauft** [comment]
Hm... what happens, when you install the following as your `on-modify` hook:
```
#!/usr/bin/env python3

print("Hook triggered!")
```

**Comment by bepolymathe** [comment]
It returns 

```
[00:12:46]  ~/.task/hooks : /usr/bin/env python3 on-modify.timewarrior 
print("Hook triggered!")
Traceback (most recent call last):
  File "/home/bepolymathe/.task/hooks/on-modify.timewarrior", line 47, in <module>
    old = json.loads(input_stream.readline().decode("utf-8", errors="replace"))
  File "/usr/lib64/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by lauft** [comment]
Did you _add_ the lines I proposed to your original hook or did you install them as a separate script next to it?
This would explain the error message
```
  File "/home/bepolymathe/.task/hooks/on-modify.timewarrior", line 47, in <module>
    old = json.loads(input_stream.readline().decode("utf-8", errors="replace"))
```
as there is no JSON parsing happening in my three lines test script. 

Ok. We know your Python seems to work (it can execute at least a simple `print`), so I assume there is something odd with the hook script. 

It's a shot in the dark, but what does `file on-modify.timewarrior` produce?

**Comment by bepolymathe** [comment]
Hi, 

The two lines wasn’t saved well :roll_eyes: Now it returns 

```
[07:54:35]  ~/.task/hooks : /usr/bin/env python3 on-modify.timewarrior 
  File "/home/bepolymathe/.task/hooks/on-modify.timewarrior", line 31
    from __future__ import print_function
    ^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

And for your second question. 

```
[07:54:39]  ~/.task/hooks : file on-modify.timewarrior
on-modify.timewarrior: Python script, ASCII text executable
```

**Comment by bepolymathe** [comment]
Okay, I found the solution. It seems that the problem was that there was an empty line (but probably with a space) at the beginning of the document. With the next start, it works again! 

![image](https://user-images.githubusercontent.com/29939805/126867337-e76e6452-bcdb-49c8-b19c-594cac611228.png)


Thank you.

**Comment by lauft** [comment]
Ok. Back one step.

Create a file `on-modify.py` with the following content 
```
#!/usr/bin/env python3

print("Hook triggered!")

```
Make it executable and run it in the shell
```
$ ./on-modify.py
```
What is the output?

If the output is only the line `Hook triggered!`, proceed below. If not, stop here and post the output. 

Next steps:
- Please remove all your hook scripts from the folder
- Install only the three line script from above
- modify a task to trigger hook execution. What is the output?

**Comment by bepolymathe** [comment]
Hi @lauft 

I can confirm that the `on-modify.py` returns `Hook triggered!`.

![image](https://user-images.githubusercontent.com/29939805/126878160-7af2fefd-61ad-4226-b7c5-76da44e968b2.png)

1. Remove all hook --» DONE
2. Install this one --» DONE
3. Output for hook execution 

![image](https://user-images.githubusercontent.com/29939805/126878240-c788ef52-e2e5-4e89-abee-b865e28f4ab8.png)

**Comment by lauft** [comment]
If it works for you it is fine with me. 🤗

However, your solution seems weird to me. Apart from the first line, those script files should allow whitespace... 🤔
